In [1]:
import time
start_time = time.time()

In [2]:
import nltk
import scipy
from nltk.tokenize import word_tokenize
from nltk.util import ngrams
import numpy as np
import re
import pickle

Split Incoming Enteries

In [3]:
def split_text(text):
    entries = []
    for i in range(len(text)):
        text_split = re.split("ENDTITLES|ENDTITLE|ENDABSTRACTS",text[i])
        title1 = text_split[0].strip()
        title2 = text_split[1].strip()
        abstract = text_split[2].replace("\r\n"," ").strip()
        decision = text_split[3].strip()
        entries.append({u'title':title1,u'abstract':abstract,u'decision':decision})
    return(entries)

Create n-grams

In [4]:
def BIGRAMS(string):
    token = nltk.word_tokenize(string)
    bigram = ngrams(token,2)
    bigrams = ', '.join(' '.join((a, b)) for a, b in bigram)
    biNoSpace = bigrams.replace(" ","")
    BIGRAM = biNoSpace.replace(",", " ")
    return BIGRAM
    
def TRIGRAMS(string):
    token = nltk.word_tokenize(string)
    trigram = ngrams(token, 3)
    trigrams = ', '.join(' '.join((a, b, c)) for a, b, c in trigram)
    triNoSpace = trigrams.replace(" ","")
    TRIGRAM = triNoSpace.replace(",", " ")
    return TRIGRAM

def QUADGRAMS(string):
    token = nltk.word_tokenize(string)
    quadgram = ngrams(token, 4)
    quadgrams = ', '.join(' '.join((a, b, c, d)) for a, b, c, d in quadgram)
    quadNoSpace = quadgrams.replace(" ","")
    QUADGRAM = quadNoSpace.replace(",", " ")  
    return QUADGRAM

Load any csv's

In [5]:
def load(name):
    with open(name+".csv", "rb") as f:
        File = np.loadtxt(f, dtype=str)
    return File

Function to Search:

In [6]:
def Search(Abs, W):
    ListOfWords = []
    match = set(Abs).intersection(set(W))
    Match = list(match)
    i=0
    while (i < len(Match)):
        ListOfWords.append(Match[i])
        #print(Match[i])
        i = i + 1  
    return ListOfWords

thing to tie it all together:

In [7]:
def Key_Num(TEXT, DICT):
    S1=Search(TEXT.split()             ,DICT)
    S2=Search(BIGRAMS(TEXT).split()    ,DICT)
    S3=Search(TRIGRAMS(TEXT).split()   ,DICT)
    S4=Search(QUADGRAMS(TEXT).split()  ,DICT)

    score1 = len(S1)
    score2 = len(S2)
    score3 = len(S3)
    score4 = len(S4)
    total =sum([score1,score2,score3,score4])
    #print("The amount of terms found is {0}" .format(score))
    return [score1, score2, score3, score4,total ]

#print(Key_Num(TEXT[1].get('abstract').lower(),key))

Test with abstract

In [8]:
text1 = "Cellular non-nonlinear network model of microbial fuel cellENDTITLECellular non-nonlinear network model of microbial fuel cell ENDTITLES A cellular non-linear network (CNN) is a uniform regular array of locally\r\nconnected continuous-state machines, or nodes, which update their states\r\nsimultaneously in discrete time. A microbial fuel cell (MFC) is an\r\nelectro-chemical reactor using the metabolism of bacteria to drive an\r\nelectrical current. In a CNN model of the MFC, each node takes a vector of\r\nstates which represent geometrical characteristics of the cell, like the\r\nelectrodes or impermeable borders, and quantify measurable properties like\r\nbacterial population, charges produced and hydrogen ions concentrations. The\r\nmodel allows the study of integral reaction of the MFC, including temporal\r\noutputs, to spatial disturbances of the bacterial population and supply of\r\nnutrients. The model can also be used to evaluate inhomogeneous configurations\r\nof bacterial populations attached on the electrode biofilms. ENDABSTRACTS Rejected"
text2 = "Electroweak and QCD corrections to Z-boson production with one b jet in a massive 5 Flavor Scheme ENDTITLE Electroweak and QCD corrections to Z-boson production with one b jet in a massive 5 Flavor Scheme ENDTITLES We compute the O(αsα2) and O(α2sα) contributions to the production cross section of a Z boson with one b jet at the Large Hadron Collider (LHC), and study their phenomenological relevance for LHC physics. The accurate prediction of hadronic Z+b-jet production is needed to control a background that greatly affects both the measurement of Higgs-boson properties and searches of new physics at the LHC. At the same time it could enable the first precise measurement of the b-quark parton distribution function. In this context b-quark mass effects become relevant and need to be studied with care, both at the level of the hard process and at the level of the initial- and final-state parton evolution. It is the aim of this paper to explore some of these issues in the framework of a massive 5 Flavor Scheme and to assess the need for both the inclusion of electroweak corrections, in addition to QCD corrections, and b-quark mass effects in the prediction of total and differential cross sections for hadronic Z+b-jet production. ENDABSTRACTS CORE"
text3="""N2HDECAY: Higgs Boson Decays in the Different Phases of the N2HDMENDTITLE
    N2HDECAY: Higgs Boson Decays in the Different Phases of the N2HDMENDTITLES
    The program N2HDECAY calculates the branching ratios and decay widths of the Higgs bosons of the Next-to-Two-Higgs-Doublet Model (N2HDM). The code incorporates the dominant higher-order effects by including QCD corrections and off-shell decay modes. The N2HDM is an extension of the Standard Model by a Higgs doublet and a real Higgs singlet. Its phenomenology can change dramatically depending on which global symmetries are broken by electroweak symmetry breaking. It can feature a large visible Higgs sector in the broken phase, behave like a 2HDM with scalar singlet dark matter in the dark singlet phase, or, in the inert doublet phase, extend an inert doublet model by mixing a singlet with the SM Higgs boson. N2HDECAY provides precise predictions for the decays of the Higgs bosons in all of these phases.ENDABSTRACTS
    CORE"""
text = [text1,text2,text3]
TEXT     = split_text(text)
TITLE= []
ABSTRACT =[]
DECISION =[]
for i in range(len(text)):
    TITLE.append(TEXT[i].get('title').lower())
    ABSTRACT.append(TEXT[i].get('abstract').lower())
    DECISION.append(TEXT[i].get('decision').lower())

key = load("KeyWords")
q=0
while (q < len(key)):
    key[q] = key[q].lower()
    q = q + 1
    

In [9]:
RESULTS = [] 
for i in range(len(text)):
    RESULTS.append(Key_Num(TITLE[i], key))
    #ListOfWords = []
    RESULTS.append(Key_Num(ABSTRACT[i], key))
    #ListOfWords=[]
    RESULTS.append(DECISION[i])

for n, i in enumerate(RESULTS):
    if i == "rejected" :
        RESULTS[n] = [0]
    if i == "core" :
        RESULTS[n] = [2]
    if i == "non-core" :
        RESULTS[n] = [1]

RESULT_array=np.reshape(np.hstack(RESULTS),(len(text),11))

In [10]:
print("My program took", time.time() - start_time, "to run")

My program took 3.290325880050659 to run


In [11]:
#save file with column headings: 
#Title:words, Title:bigrams, Title:trigrams, Title:quadgrams, Title:total, Abstract:words, Abstract:bigrams, Abstract:trigrams, Abstract:quadgrams, Abstract:total, classification
def output_file(name,output):
    with open(name+".pkl",'wb') as f:
        pickle.dump(output,f)
output_file('keyword_occurances',RESULT_array)            

In [12]:
with open('keyword_occurances.pkl','rb') as f:
    mydata= pickle.load(f)


[[ 2  0  0  0  2  7  0  0  0  7  0]
 [ 5  0  0  0  5 13  3  1  0 17  2]
 [ 2  0  0  0  2 12  5  1  1 19  2]]
